// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"steam-tracker/internal/client/steam"
	"steam-tracker/internal/config"
	"steam-tracker/internal/db"
	"steam-tracker/internal/handler/game"
	"steam-tracker/internal/handler/tracked_game"
	"steam-tracker/internal/notifier"
	"steam-tracker/internal/queue"
	"steam-tracker/internal/repository/game"
	"steam-tracker/internal/repository/price_history"
	"steam-tracker/internal/repository/tracked_game"
	"steam-tracker/internal/repository/user"
	"steam-tracker/internal/router"
	"steam-tracker/internal/server"
	"steam-tracker/internal/service/game"
	"steam-tracker/internal/service/price_history"
	"steam-tracker/internal/service/tracked_game"
)

// Injectors from wire.go:

func Bootstrap() (*App, error) {
	configConfig := config.New()
	sqlDB, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	repository := userrepo.New(sqlDB)
	steamSteam := steam.New()
	gamerepoRepository := gamerepo.New(sqlDB)
	service := gameservice.New(steamSteam, gamerepoRepository)
	handler := gamehandler.New(service)
	trackedgamerepoRepository := trackedgamerepo.New(sqlDB)
	trackedgameserviceService := trackedgameservice.New(trackedgamerepoRepository)
	trackedgamehandlerHandler := trackedgamehandler.New(trackedgameserviceService)
	mux := router.New(repository, handler, trackedgamehandlerHandler)
	serverServer := server.New(configConfig, mux)
	pricehistoryrepoRepository := pricehistoryrepo.New(sqlDB)
	client := queue.NewClient(configConfig)
	pricehistoryserviceService := pricehistoryservice.New(trackedgamerepoRepository, pricehistoryrepoRepository, steamSteam, client)
	emailTarget := notifier.NewEmailTarget()
	emailPriceChanged := notifier.NewEmailPriceChanged()
	worker := queue.NewWorker(configConfig, emailTarget, emailPriceChanged)
	app := &App{
		Server:  serverServer,
		Tracker: pricehistoryserviceService,
		Worker:  worker,
	}
	return app, nil
}

// wire.go:

type App struct {
	Server  *server.Server
	Tracker *pricehistoryservice.Service
	Worker  *queue.Worker
}
