// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go.rest.api/internal/client"
	"go.rest.api/internal/config"
	"go.rest.api/internal/db"
	"go.rest.api/internal/handler/game"
	"go.rest.api/internal/repository/game"
	"go.rest.api/internal/repository/user"
	"go.rest.api/internal/router"
	"go.rest.api/internal/server"
	"go.rest.api/internal/service/game"
)

// Injectors from wire.go:

func Bootstrap() (*server.Server, error) {
	configConfig := config.New()
	sqlDB, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	repository := userrepo.New(sqlDB)
	steamClient := client.NewClient()
	gamerepoRepository := gamerepo.New(sqlDB)
	service := gameservice.New(steamClient, gamerepoRepository)
	handler := gamehandler.New(service)
	mux := router.New(repository, handler)
	serverServer := server.New(configConfig, mux)
	return serverServer, nil
}
