// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go.rest.api/internal/config"
	"go.rest.api/internal/db"
	"go.rest.api/internal/repository/user"
	"go.rest.api/internal/router"
	"go.rest.api/internal/server"
)

// Injectors from wire.go:

func Bootstrap() (*server.Server, error) {
	configConfig := config.New()
	sqlDB, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	repository := userrepo.New(sqlDB)
	mux := router.New(repository)
	serverServer := server.New(configConfig, mux)
	return serverServer, nil
}
